echo ;
echo ;
echo ;
rm outfile;
./calculator < test.cal >> outfile;
echo --------- 1 end;
./calculator < test2.cal >> outfile;
echo --------- 2 end;
./calculator < test4.cal >> outfile;
echo --------- 4 end;
./calculator < test5.cal >> outfile;
echo --------- 5 end;
./calculator < test6.cal >> outfile;
echo --------- 6 end;
./calculator < wrong_test7.cal >>outfile;
echo --------- 7 end;
echo ;
echo ;
echo ;